version: '3.1'

services:
  mariadb:
    image: mariadb:10.6.4
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8888:8080
    links:
      - mariadb

volumes:
  database:
